### ISSUE TITLE
compatibiliy problem between ICanHaz and zepto 0.5 ?

### ISSUE THREAD

**Issue by Mikashv** [HenrikJoreteg/ICanHaz.js#12]
When i use very simply  IcanHaz  and the 0.5 zepto version, iCanHaz do is job but after doing it,  i have an error like :  Uncaught Error: TYPE_MISMATCH_ERR: DOM Exception 17 and zepto dont work anymore.
Any Idea ?

**Comment by HenrikJoreteg** [comment]
It's likely some reverse-incompatible updates to Zepto that need to be addressed. Thanks for pointing this out.

**Comment by HenrikJoreteg** [comment]
I'm going to close this for now as tests are passing in the "module" branch that uses the latest zepto. let me know if you're still having trouble.
