### ISSUE TITLE
remove the need for class="partial"

### ISSUE THREAD

**Issue by reactormonk** [HenrikJoreteg/ICanHaz.js#15]
You need to mark partials with class="partial", which is overcomplicating things. Why not be able to use every template as partial?

**Comment by HenrikJoreteg** [comment]
Makes a lot of sense to me. I don't see any reason not to do this.

**Comment by mspyratos** [comment]
I agree with this. Just looking for a way to call a partial directly. Cause sometimes you just want to regenerate list items not the wrapper :)

**Comment by boxxxie** [comment]
sometimes when i want a partial to be a template i have to make 2 scripts, one that just calls the partial. redundant and error prone.

**Comment by HenrikJoreteg** [comment]
If you take a look at the "module" branch, this has actually been done. I'm just going to do a bit more testing before I merge it into master, but it does work this way now.

Thanks for the suggestion!

**Comment by nwhittaker** [comment]
Treating every template as a partial can introduce a serious performance bottleneck. It causes Mustache to compile all the defined templates at once on the first call to "to_html".
