### ISSUE TITLE
Request: i18n

### ISSUE THREAD

**Issue by milani** [HenrikJoreteg/ICanHaz.js#27]
Hi,

I think adding an internationalization plugin would be awesome. Using a template engine with internationalization makes life easy for developers!

One possible solution is to trigger an event with generated content as argument. in this way developers can use their own internationalization plugins as callback functions to this event:)

**Comment by HenrikJoreteg** [comment]
I think this is perhaps best handled on the Mustache project itself, no? ICanHaz bundles mustache. Also if you do add that to another version of Mustache, there's a version of ICanHaz in the "module" branch that doesn't bundle mustache at all, so you can bring your own. Let me know if this makes sense. Here's the mustache.js project on github: https://github.com/janl/mustache.js

Cheers!

**Comment by milani** [comment]
In mustache one should provide templates for each language in a specific json file and load it depending on the language user choose. It's a good solution. Thank you.
