### ISSUE TITLE
multi level objects

### ISSUE THREAD

**Issue by fightbulc** [HenrikJoreteg/ICanHaz.js#31]
Hi there, the current version wont parse e.g. "user.name". The issue lies within mustache 0.3.0
I updated mustache to 0.4.0-dev which solved the issue.

https://gist.github.com/1373235

Cheers

**Comment by HenrikJoreteg** [comment]
Yep, the mustache version that is bundled with the current "master" is old. If you want to look at the "module" branch I've got a version in there built with a later version of mustache, as well as one that doesn't bundle it, so you can pick whichever version you want. Hope that helps!
