### ISSUE TITLE
's' is undefined

### ISSUE THREAD

**Issue by ErikGoldman** [HenrikJoreteg/ICanHaz.js#34]
where it says

"else return s.replace(/^\s+/, '').replace(/\s+$/, '');"

I think you mean

"else return stuff.replace(/^\s+/, '').replace(/\s+$/, '');"

and it's throwing errors in IE8.

**Comment by HenrikJoreteg** [comment]
ah, yes. This has actually been fixed in the "module" branch which I'll be (hopefully) merging into master soon. Once it's been a bit more tested. Thanks!
