### ISSUE TITLE
Compatibility with RequireJS / AMD

### ISSUE THREAD

**Issue by leonth** [HenrikJoreteg/ICanHaz.js#35]
As I see it, the current implementation of CommonJS conflicts with requirejs, arguably the most popular AMD (Async Module Definition) implementation. When using RequireJS, I get `Uncaught ReferenceError: module is not defined` at line 403 (when module.exports is involved).

**Comment by HenrikJoreteg** [comment]
I'm not entirely sure this is AMD compatible now, but as of the lastest version it works as a CommonJS module. Please let me know if it works. Cheers!

**Comment by tyaakow** [comment]
I'm using main ICanHaz.js file, freshly cloned, and it throws me a "module not defined" with require.js,
issue being with 

`if (typeof require !== 'undefined') {
 module.exports = ich;`

 on 523. line.
If there is a solution, I'd be delighted to know.
Should I require mustache separately
(cause require tries to import single variable from a file, but mustache & ich bundle has two?)
I'll try that..
I'll also try to convert it to require module with r.js tool..

**Comment by tyaakow** [comment]
Yep, r.js did it.

**Comment by pierot** [comment]
Is there a definite fix for this?

**Comment by tyaakow** [comment]
use r.js tool to convert. It worked for me.

**Comment by HenrikJoreteg** [comment]
As this can be solved by a require.js shim I'll leave this be. Thanks, though.

**Comment by pierot** [comment]
You could, maybe, add a short explanation to the README. Guiding people,
like me, towards a solution.

Pieter Michels
+32 499 20 76 14
pieter@noort.be

On Mon, Feb 27, 2012 at 06:52, Henrik Joreteg <
reply@reply.github.com

**Comment by FxIII** [comment]
It seams that using require.js shim is does not solve the problem since the global `require` is not `undefined` when ich loads.
The point is that checking `if(typeof require !== 'undefined')` is the wrong test (may produce false positives), checking for the existence of both require and model may be useful; the top would be check for CommonJS presence.

**Comment by dazld** [comment]
@jvashishtha that fix looks good, thanks for sharing.

**Comment by LeonardoGentile** [comment]
Thank @jvashishtha that worked for me also! Why isn't your fix being integrated in the latest version? 
It may help other mates out there.

**Comment by jogi** [comment]
@LeonardoGentile I would like to get it integrated. But the issue can also be solved by require.js shim as mentioned by the author. That's the reason the fix was not integrated.

**Comment by LeonardoGentile** [comment]
@jvashishtha I've tried it with require.js shim and it did not work for me. The only way to make it works was using your modified version.
