### ISSUE TITLE
s is undefined in browsers that don't support trim

### ISSUE THREAD

**Issue by mjuniper** [HenrikJoreteg/ICanHaz.js#37]
There is an error at line 338:

else return s.replace(/^\s+/, '').replace(/\s+$/, '');

should be:

else return stuff.replace(/^\s+/, '').replace(/\s+$/, '');

**Comment by HenrikJoreteg** [comment]
fixed in latest, thanks.

**Comment by mjuniper** [comment]
Thank you. Great work; I love ICanHaz!
