### ISSUE TITLE
Empty array if there is returned if there is no HTML tag in the template.

### ISSUE THREAD

**Issue by Sephi-Chan** [HenrikJoreteg/ICanHaz.js#38]
Hello,

I noticed a bug when I use very simple templates, without HTML tag. For instance:

``` html
<script id='turnCounter' type='text/html'>
  Turn {{turn}}
</script>
```

When I compile it, it fails.

``` javascript
ich.turnCounter({ turn: 3 }) // => []
```

I would expect to have "Turn 3". Any idea?

Thanks for ICanHaz anyway, it's very cool with more real-world templates ! ;)

**Comment by HenrikJoreteg** [comment]
Just pass `true` as the second argument and it won't jQuerify it.

```
ich.turnCounter({ turn: 3 }, true);
```
