### ISSUE TITLE
dot notation?

### ISSUE THREAD

**Issue by philfreo** [HenrikJoreteg/ICanHaz.js#42]
Dot notation is supposed to work per the mustache docs (eg `{{ name.first }}`)

On the latest icanhaz.js the dot notation doesn't seem to be working.

I had a context like this 
`{ firstname: 'john', a: { blah: 'foo' } }`

and `{{ firstname }}` works

but `{{ a.blah }}` doesn't work

though a (poor) workaround that seems to work is `{{ #a }}{{ blah }}{{ /a }}`

Perhaps this is a problem with being on an older mustache version?

**Comment by HenrikJoreteg** [comment]
This is in the latest version that I just pushed.

**Comment by philfreo** [comment]
It seems to be buggy...

```
<script type="text/html" id="testingTemplate">
    <div>
        {{ foo }}
        {{ #bar }}<b>{{ #bar.baz }}</b>{{ /bar }}
    </div>
</script>
```

with

```
{
    foo: 'foo',
    bar: {
        baz: 'baz'
    }
}
```

gives me Uncaught ReferenceError: file is not defined in ICanHaz.min.js:4

**Comment by philfreo** [comment]
(I don't have permission to reopen this issue but it should be)

**Comment by HenrikJoreteg** [comment]
Read up on the mustache docs, don't use the "#" inside the loop.

Also, realize ICanHaz just bundles mustache.js all the rendering is
handled by it, not ICH.

On Jan 23, 2012, at 10:20, Phil Freo
reply@reply.github.com
wrote:

**Comment by philfreo** [comment]
Then how are you supposed to handle falsy cases (so as to not output `<b>` above if there is `bar` is null)? I thought I was doing it correctly based on the section "FALSE VALUES OR EMPTY LISTS" from https://github.com/janl/mustache.js

**Comment by HenrikJoreteg** [comment]
``` html
<div>
    {{ foo }}
    {{ #bar }}<b>{{ bar.baz }}</b>{{ /bar }}
</div>
```

**Comment by philfreo** [comment]
Sorry -- that was a silly typo on my part which hid the real issue. The real bug is:

```
<script type="text/html" id="testingTemplate">
    <div>
        Test: {{ foo }}
        {{ #bar }}*{{ bar }}*{{ /bar }}
    </div>
</script>
```

data source:

```
TESTING_DATA = [
    {
        'foo': 'foo1',
        'bar': null
    },
    {
        'foo': 'foo2',
        'bar': false,
    },
    {
        'foo': 'foo3',
        'bar': 'bar1'
    }
];
```

Gets rendered as:

```
Test: foo1 **
Test: foo2
Test: foo3 *bar1*
```

Instead of the expected:

```
Test: foo1
Test: foo2
Test: foo3 *bar1*
```

Specifically the mustache.js docs say "If the person key exists and has a value of null, undefined, or false, or is an empty list, the block will not be rendered." but it seems that `null` is not being treated correctly like `false` is.

Is this a problem with icanhaz.js or mustache.js?

**Comment by HenrikJoreteg** [comment]
yeah, anything related to template rendering is Mustache.

**Comment by philfreo** [comment]
Here's why I suspected it might be related to ICanHaz - or at least the version of Mustache.js bundled with ICanHaz.js

In testing, when I use just:

```
<script type="text/javascript" src="https://raw.github.com/andyet/ICanHaz.js/master/ICanHaz.min.js"></script>
```

Then my test fails.

But if I use:

```
<script type="text/javascript" src="https://raw.github.com/janl/mustache.js/master/mustache.js"></script>
<script type="text/javascript" src="https://raw.github.com/andyet/ICanHaz.js/master/ICanHaz-no-mustache.min.js"></script>
```

Then it works.

**Comment by HenrikJoreteg** [comment]
grab the latest ICanHaz. At one point, right when tweeted about it I realized that I still had the old mustache in there. I fixed it right away, but you _could_ have that version. 
- Henrik

**Comment by philfreo** [comment]
An hour ago I tried it literally with the hotlinked to master github files (exactly as my post shows) and it had the problem

**Comment by HenrikJoreteg** [comment]
can you post a gist of exactly what you're doing so I can try to reproduce it?

**Comment by HenrikJoreteg** [comment]
I figured it out, thanks for your help on this. That's what I get for bundling an in-progress version of mustache. Now bundles with 0.4.0. This should fix it. Let me know if that's not the case.
