### ISSUE TITLE
update mustache.js to latest version

### ISSUE THREAD

**Issue by d1rk** [HenrikJoreteg/ICanHaz.js#49]
I have seen forks that already have that, like the one from @jimmybyrum - I think at least dot.notation is worth it.

**Comment by HenrikJoreteg** [comment]
Howdy, @d1rk.

Dot-notation is already in the current version: https://github.com/HenrikJoreteg/ICanHaz.js/blob/master/ICanHaz.js#L321

Or if you want to use a specific version of mustache, you can use one of the "no-mustache" builds you can just include whatever version of mustache you want. As long as it has a Mustache.to_html function it should work.

**Comment by d1rk** [comment]
I did not notice the support for dot-notation, i'll have to try again. Thanks for your feedback.
