### ISSUE TITLE
more generic for any template engine?

### ISSUE THREAD

**Issue by muescha** [HenrikJoreteg/ICanHaz.js#6]
would it be more nice to have it more generic and not tie to a special template engine?

it should be like rack - a generic interface for any template engine and you can switch it.

**Comment by HenrikJoreteg** [comment]
I've had similar thoughts. I really do like the convenience of simply doing a single-file include, but I've had thoughts of using my `makefile` to build different versions for different templating engines. For example: `ICanHaz.mustache.js` and `ICanHaz.jade.js`. But, I'm not sold on it yet. What templating language do you wish it would support?

**Comment by HenrikJoreteg** [comment]
closing, because no clear implementation plan.
