### ISSUE TITLE
Render template with dynamic template name

### ISSUE THREAD

**Issue by ducin** [HenrikJoreteg/ICanHaz.js#60]
I've got two templates defined: `incomeFormTemplate` and `outcomeFormTemplate`. They get the same parameters to be rendered.

Now I can render them like the following:

```
ich.incomeFormTemplate(params)
ich.outcomeFormTemplate(params)
```

Is there any way to pass the template name as the parameter to achieve something like:

```
ich.render('incomeFormTemplate', params)
```

If so, could it be included in the docs maybe?

**Comment by ducin** [comment]
Hm, I've just found out, that it's possible to call:

```
ich['templateName'](params)
```

if this is a trusted solution, I think it's worth mentioning this in the official docs ;)

**Comment by HenrikJoreteg** [comment]
The reason this isn't mentioned in the docs is that it's a feature of javascript, the language, not of ICanHaz.  

in JS the following two statements are equivalent:

``` js
object.property
```

``` js
object['property']
```
