### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by kendagriff** [HenrikJoreteg/ICanHaz.js#8]
Is there by chance a way to script a callback while using icanhaz.js?

For example, if I call ich.user(), and my template is <script id="user" type="text/html">, I'd like to have a callback fire each time that template is generated. Does that make sense?

**Comment by HenrikJoreteg** [comment]
I see what you're saying, could you explain what you'd use that for? In general, using callbacks is a very useful pattern, however, it seems to me that template rendering is just the end result of your view logic. Off the top of my head I'm having trouble seeing a great use for them in this case. But, i'm all ears...

**Comment by kendagriff** [comment]
Yeah, I'm wondering why I even asked this question, hehe.
